services:
  pipeline:
    build: .
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - DBT_PROFILES_DIR=/workspace/dbt
    command: python src/flow.py

  prefect-server:
    build: .
    volumes:
      - .:/workspace
      - prefect-data:/root/.prefect
    working_dir: /workspace
    ports:
      - "4200:4200"
    environment:
      - PREFECT_HOME=/root/.prefect
    command: prefect server start --host 0.0.0.0

  dashboard:
    build: .
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "8050:8050"
    environment:
      - DB_PATH=/workspace/ecommerce_analytics.db
    depends_on:
      - pipeline
    command: python dashboard/app.py


volumes:
  prefect-data:
